from pyspark.sql import Row

sent_record_example = {
    'model_original_model': 'waterfalltoprank',
    'source_sender': 'userconversationdecider',
    'device_os_version': '10.2.1',
    'device_vendor': 'apple',
    'background_image_attribute': 'illustration',
    'priority_method': 'usersimilarity',
    'is_user_in_new_content_exploration_group': False,
    'device_model': 'iphone9,2',
    'program_name': 'sprint whitelist',
    'chosen_conversation_rank': 0,
    'segments_attribute': ['device_function', 'phone_setup'],
    'sales_source': 'web',
    'model_id': 'waterfalltoprank',
    'notification_preview_message': 'bla bla',
    'app_version': '3.512.0',
    'device_type_mobile': False,
    'notification_loading_method': 'contentvieweronly',
    'content_channels_search_results': True,
    'device_os_type': 'ios',
    'expanded_notification_exists': False,
    'installation_source': 'installsourceVal',
    'content_item_category': 'educational',
    'content_channels_card': True,
    'app_badge_count_method': 'always1',
    'carrier_name': 'sprint',
    'message_id': '20180601013214536_ab79151d-2796-447c-b3fe-c76c4f07b7eb',
    'registration_country': 'us and a',
    'expanded_notification_is_enabled': False,
    'date': '2018-06-01',
    'min_days_between_notifications': 3,
    'model_id_version': 'v2',
    'contenttype_attribute': ['tutorial'],
    'sent_timestamp': 1527805957,
    'form_factor': 'mobile',
    'notificationcopy_attribute': ['asd'],
    'sent_localtime': 1527805957,
    'device_features_attribute': ['calling_and_messaging'],
    'format_attribute': 'article',
    'device_id': '772e047c-d9a4-4cf2-bf95-cde10bee1628',
    'device_type_tablet': False,
    'item_subject': ['empty'],
    'card_background_attribute': 'card background atr',
    'notification_preview_headline': 'set up your visual voicemail',
    'registration_region': 'sweet home alabama',
    'is_pos_customer': False,
    'possible_conversations_count': 80,
    'show_footer': True,
    'content_channels_notification': True,
    'notification_copy_attributes': ['descriptive'],
    'days_from_eula_approval': 439,
    'app_badge_count': 1,
    'notification_render_type': 'static',
    'registration_city': 'shasha',
    'notification_copy_original_variant_count': 1,
    'complexity_attribute': 1,
    'notification_copy_variant_label': 'foo foo',
    'model_recommendation_probability': 0.06744868,
    'word_count': 138,
    'sent_local_day_of_week': 'thursday',
    'timeline_enabled': True,
    'model_fallback_level': 1,
    'message_type': '24573_how-to-set-up-voicemail-ios',
    'home_tier': 'homesupport',
    'background_image_original_variant_count': 1,
    'sent_as_high_priority': False,
    'notification_frequency_model_id': 'random',
    'subject_attribute': ['device_function']
}

flatten_data_record_example = {'model_original_model': 'random',
                               'source_sender': 'userconversationdecider',
                               'device_os_version': '7.0',
                               'device_vendor': 'samsung',
                               'background_image_attribute': 'illustration',
                               'actions': [Row(action='backbutton', timestamp=1328065123)],
                               'recieved': 1,
                               'recieved_timestamp': 1111805957,
                               'priority_method': 'random',
                               'is_user_in_new_content_exploration_group': False,
                               'device_model': 'sm-g920v',
                               'device_id': '99a08bf3-4681-4c74-a25e-e67b64ad27ad',
                               'program_name': 'tmp md',
                               'chosen_conversation_rank': 0,
                               'segments_attribute': ['device_function', 'phone_setup'],
                               'sales_source': '',
                               'model_id': 'random',
                               'notification_preview_message': '',
                               'sent_local_day_of_week': 'thursday',
                               'sent_localtime': 1555505957,
                               'device_type_mobile': False,
                               'view': 1,
                               'view_timestamp': 1222205957,
                               'notification_loading_method': 'contentvieweronly',
                               'content_channels_search_results': True,
                               'device_os_type': 'android',
                               'expanded_notification_exists': False,
                               'installation_source': 'tech-unique-sms',
                               'content_item_category': 'educational',
                               'content_channels_card': True,
                               'app_badge_count_method': 'always1',
                               'carrier_name': 'verizon',
                               'message_id': '20180531235940705_4cb9741e-f221-432a-9023-6a4e5c906c38',
                               'registration_country': 'united states',
                               'expanded_notification_is_enabled': False,
                               'date': '2018-06-01',
                               'min_days_between_notifications': 10,
                               'model_id_version': 'v2',
                               'scroll_depth': 75,
                               'contenttype_attribute': ['informational'],
                               'sent_timestamp': 1527805952,
                               'feedback_value': True,
                               'form_factor': 'mobile',
                               'notificationcopy_attribute': ['question', 'teaser'],
                               'app_version': '4.331.8',
                               'device_features_attribute': [''],
                               'format_attribute': 'article',
                               'content_channels_notification': True,
                               'device_type_tablet': False,
                               'dismiss': 1,
                               'dismiss_timestamp': 1333305952,
                               'card_background_attribute': 'illustration',
                               'notification_preview_headline': 'planning a vacation?',
                               'registration_region': 'oregon',
                               'is_pos_customer': False,
                               'possible_conversations_count': 140,
                               'time_on_page': 16.81,
                               'device_locale': 'en_us',
                               'item_subject': ['empty'],
                               'show_footer': True,
                               'notification_copy_attributes': ['question', 'teaser'],
                               'days_from_eula_approval': 101,
                               'app_badge_count': 1,
                               'notification_render_type': 'static',
                               'registration_city': 'albany',
                               'agent_locale': 'en_us',
                               'notification_copy_original_variant_count': 1,
                               'complexity_attribute': 1,
                               'notification_copy_variant_label': '',
                               'model_recommendation_probability': 0.16,
                               'word_count': 177,
                               'feedback_module_impression': 0,
                               'feedback_module_impression_timestamp': 1444405952,
                               'timeline_enabled': True,
                               'model_fallback_level': 1,
                               'message_type': '51690_prepare-your-mobile-for-traveling-abroad-both',
                               'home_tier': 'insurance',
                               'background_image_original_variant_count': 1,
                               'sent_as_high_priority': True,
                               'notification_frequency_model_id': 'clustering',
                               'subject_attribute': ['device_function', 'leisure_and_entertainment']}
